# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodStory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodStory

# FireBase
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'

# Util
  pod 'IQKeyboardManagerSwift'

# Zip
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Zip', '~> 2.1'

# FsCalendar
  pod 'FSCalendar'

# Realm
  pod 'RealmSwift', '~>10'

end
